- name: Trigger Codemagic workflow
  # You may pin to the exact commit or the version.
  # uses: codemagic-ci-cd/trigger-codemagic-workflow-action@9ffb727bfe2f7f3a0d429fe157099e5cc183566c
  uses: codemagic-ci-cd/trigger-codemagic-workflow-action@v1.0.0
  with:
    # Codemagic application ID
    app-id: 
    # Codemagic workflow ID
    workflow-id: 
    # Codemagic API token
    token: 
    # GitHub event branch override
    branch: # optional
    # GitHub event tag override
    tag: # optional
    # Build labels
    labels: # optional
    # Xcode version
    xcode: # optional
    # Flutter version
    flutter: # optional
    # CocoaPods version
    cocoapods: # optional
    # Node version
    node: # optional
    # NPM version
    npm: # optional
    # NDK version
    ndk: # optional
    # Java version
    java: # optional
    # Ruby version
    ruby: # optional
